---
# handlers file for setup-apache

- name: start httpd service
  service:
    name: httpd
    state: started

- name: Start Apache
  service:
    name: apache2
    state: started

- name:  Restart httpd
  service:
    name: httpd
    state: restarted

- name:  Restart apache2
  service:
    name: apache2
    state: restarted
 
