---
- name: This playbook is to copy a file
  hosts: all
  become: true
  tasks:
  - name: copy a file
    copy:
      src: /opt/ansible/testfile.txt
      dest: /home/ansadmin
      mode: 0600
      owner: john
