---
- name: This playbook is to create a file or dir
  hosts: all
  #become: true
  tasks:
  - name: create a file
    file:
      path: /home/ansadmin/demofile
      state: touch
  - name: create a directory
    file:
      path: /home/ansadmin/dir1
      state: directory    
