---
- name: This is to create a new user
  hosts: all
  become: true
  #vars:
  #  user: jeff 
  vars_files:
    - users.yml  
  tasks:
  - name: Creating user {{ user }}
    user: 
      name: "{{ user }}"

